[package]
name = "rinha-fraud-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "lb"
path = "src/bin/lb.rs"

[dependencies]
memmap2 = "0.9"
mimalloc = { version = "0.1", default-features = false }
libc = "0.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
