services:
  lb:
    image: ghcr.io/atomosdovini/rinha-fraud-rust:latest
    entrypoint: ["/lb"]
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - UPSTREAMS=/sockets/api1.sock,/sockets/api2.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20M"

  api1:
    image: ghcr.io/atomosdovini/rinha-fraud-rust:latest
    environment:
      - LISTEN=/sockets/api1.sock
      - INDEX_PATH=/index/index.bin
      - NPROBE=20
      - FAST_NPROBE=1
      - ADAPTIVE_MIN=2
      - ADAPTIVE_MAX=4
      - EXTREME0_WORST_THRESHOLD=3501932
      - EXTREME1_WORST_THRESHOLD=3569273
      - EXTREME5_WORST_THRESHOLD=4594089
      - REPAIR_MIN=99
      - REPAIR_MAX=0
      - INDEX_MMAP=1
      - MALLOC_ARENA_MAX=1
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  api2:
    image: ghcr.io/atomosdovini/rinha-fraud-rust:latest
    environment:
      - LISTEN=/sockets/api2.sock
      - INDEX_PATH=/index/index.bin
      - NPROBE=20
      - FAST_NPROBE=1
      - ADAPTIVE_MIN=2
      - ADAPTIVE_MAX=4
      - EXTREME0_WORST_THRESHOLD=3501932
      - EXTREME1_WORST_THRESHOLD=3569273
      - EXTREME5_WORST_THRESHOLD=4594089
      - REPAIR_MIN=99
      - REPAIR_MAX=0
      - INDEX_MMAP=1
      - MALLOC_ARENA_MAX=1
    volumes:
      - sockets:/sockets
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

volumes:
  sockets:
